apiVersion: v1
kind: Service
metadata:
  name: stats
  namespace: payfloor
  labels:
    app.kubernetes.io/name: stats
    app.kubernetes.io/part-of: payfloor
spec:
  type: ClusterIP
  selector:
    app: stats
  ports:
    - name: http
      port: 4005
      targetPort: 4005
