apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: payfloor
  labels:
    app.kubernetes.io/name: search
    app.kubernetes.io/part-of: payfloor
spec:
  type: ClusterIP
  selector:
    app: search
  ports:
    - name: http
      port: 4004
      targetPort: 4004
